spring.datasource.url=jdbc:postgresql://postgres:5432/userdb
spring.datasource.username=appuser
spring.datasource.password=apppassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
otel.service.name=spring-opentelemetry-jaeger
otel.exporter.otlp.endpoint=http://jaeger:4317
management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.mapper-locations=classpath:mapper/*.xml
spring.h2.console.enabled=false
spring.sql.init.mode=never